"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, LoaderCircle, MessageSquareWarning, Plus, RefreshCw, ShieldCheck, Trash2, UserCog, Users } from "lucide-react";
import BrandLogo from "./BrandLogo";
import ThemeToggle from "./ThemeToggle";

type AdminUser = { id: string; email?: string; created_at: string; banned_until?: string; app_metadata: { requestlab_role?: string }; user_metadata: { full_name?: string } };
type Complaint = { id:string; user_email:string; subject:string; message:string; status:string; admin_response:string; created_at:string };

export default function AdminPortal({ currentUserId }: { currentUserId: string }) {
  const [users,setUsers]=useState<AdminUser[]>([]); const [complaints,setComplaints]=useState<Complaint[]>([]);
  const [draft,setDraft]=useState({email:"",password:"",fullName:"",role:"user"}); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const load=useCallback(async()=>{setBusy("load");setError("");try{const [u,c]=await Promise.all([fetch("/api/admin/users"),fetch("/api/complaints")]);const ud=await u.json(),cd=await c.json();if(!u.ok)throw new Error(ud.error);if(!c.ok)throw new Error(cd.error);setUsers(ud.users||[]);setComplaints(cd.complaints||[]);}catch(e){setError((e as Error).message)}finally{setBusy("")}},[]);
  useEffect(()=>{void load()},[load]);
  const createUser=(e:FormEvent)=>{e.preventDefault();setBusy("create");setError("");fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setDraft({email:"",password:"",fullName:"",role:"user"});await load()}).catch(e=>setError(e.message)).finally(()=>setBusy(""))};
  const updateUser=async(id:string,body:Record<string,unknown>)=>{setBusy(id);setError("");try{const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...body})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}};
  const deleteUser=async(id:string)=>{if(!confirm("Permanently delete this user?"))return;setBusy(id);const r=await fetch(`/api/admin/users?id=${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)setError(d.error);else await load();setBusy("")};
  const updateComplaint=async(item:Complaint,status:string,adminResponse:string)=>{setBusy(item.id);const r=await fetch("/api/complaints",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,status,adminResponse})});const d=await r.json();if(!r.ok)setError(d.error);else await load();setBusy("")};
  return <main className="portal-page admin-page"><header className="portal-header"><BrandLogo/><nav><Link href="/app"><ArrowLeft size={15}/> Workspace</Link><Link href="/settings">Settings</Link><ThemeToggle/></nav></header><div className="admin-wrap"><div className="admin-title"><div><span className="section-kicker">System administration</span><h1>Admin portal</h1><p>Manage access, account status, roles, and user complaints.</p></div><button className="secondary" onClick={()=>void load()} disabled={busy==="load"}><RefreshCw className={busy==="load"?"spin":""}/> Refresh</button></div>{error&&<div className="portal-alert error">{error}</div>}<div className="admin-stats"><div><Users/><strong>{users.length}</strong><span>Total users</span></div><div><ShieldCheck/><strong>{users.filter(u=>u.app_metadata?.requestlab_role==="admin").length}</strong><span>Administrators</span></div><div><MessageSquareWarning/><strong>{complaints.filter(c=>c.status!=="resolved").length}</strong><span>Open complaints</span></div></div>
  <form className="portal-card admin-create" onSubmit={createUser}><header><Plus/><div><h2>Add a user</h2><p>Accounts created here are confirmed immediately.</p></div></header><div className="portal-fields"><label>Full name<input required value={draft.fullName} onChange={e=>setDraft({...draft,fullName:e.target.value})}/></label><label>Email<input required type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Temporary password<input required minLength={8} type="password" value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></label><label>Role<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="user">User</option><option value="admin">Administrator</option></select></label></div><button className="primary" disabled={busy==="create"}>{busy==="create"?<LoaderCircle className="spin"/>:<Plus/>} Create user</button></form>
  <section className="portal-card"><header><UserCog/><div><h2>User management</h2><p>Change roles, issue a new password, suspend, or remove accounts.</p></div></header><div className="admin-table"><div className="admin-row admin-row-head"><span>User</span><span>Role</span><span>Created</span><span>Actions</span></div>{users.map(user=><div className="admin-row" key={user.id}><span><strong>{user.user_metadata?.full_name||"Unnamed user"}</strong><small>{user.email}</small></span><select value={user.app_metadata?.requestlab_role||"user"} disabled={user.id===currentUserId||busy===user.id} onChange={e=>void updateUser(user.id,{role:e.target.value})}><option value="user">User</option><option value="admin">Admin</option></select><span>{new Date(user.created_at).toLocaleDateString()}</span><span className="row-actions"><button className="secondary" onClick={()=>{const p=prompt("Enter a new password (minimum 8 characters)");if(p)void updateUser(user.id,{password:p})}}>Password</button><button className="secondary" disabled={user.id===currentUserId} onClick={()=>void updateUser(user.id,{banned:!user.banned_until})}>{user.banned_until?"Restore":"Suspend"}</button><button className="icon-button danger" disabled={user.id===currentUserId} onClick={()=>void deleteUser(user.id)}><Trash2/></button></span></div>)}</div></section>
  <section className="portal-card"><header><MessageSquareWarning/><div><h2>Complaints inbox</h2><p>Review reports and communicate their resolution.</p></div></header><div className="admin-complaints">{complaints.length?complaints.map(item=><ComplaintEditor key={item.id} item={item} busy={busy===item.id} onSave={updateComplaint}/>):<p className="muted">No complaints have been submitted.</p>}</div></section></div></main>;
}

function ComplaintEditor({item,busy,onSave}:{item:Complaint;busy:boolean;onSave:(item:Complaint,status:string,response:string)=>Promise<void>}){const[status,setStatus]=useState(item.status);const[response,setResponse]=useState(item.admin_response||"");return <article className="complaint-editor"><div><span><strong>{item.subject}</strong><small>{item.user_email} · {new Date(item.created_at).toLocaleString()}</small></span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></div><p>{item.message}</p><textarea placeholder="Write a response to the user…" value={response} onChange={e=>setResponse(e.target.value)}/><button className="primary" disabled={busy} onClick={()=>void onSave(item,status,response)}>{busy?<LoaderCircle className="spin"/>:"Save response"}</button></article>}
