"use client";

import Link from "next/link";
import { FormEvent, KeyboardEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, LoaderCircle, MessageSquareWarning, Plus, RefreshCw, Search, ShieldCheck, Trash2, UserCog, Users } from "lucide-react";
import BrandLogo from "./BrandLogo";
import ThemeToggle from "./ThemeToggle";
import { useAppDialog } from "./AppDialog";

type AdminUser = { id:string; email?:string; created_at:string; banned_until?:string; app_metadata:{requestlab_role?:string}; user_metadata:{full_name?:string} };
type Complaint = { id:string; user_email:string; subject:string; message:string; status:string; admin_response:string; created_at:string };
type Direction = "asc" | "desc";
const PAGE_SIZES = [10, 25, 50, 100];
const text = (value:unknown) => String(value ?? "").toLowerCase();

function SortButton({label,active,direction,onClick}:{label:string;active:boolean;direction:Direction;onClick:()=>void}) {
  return <button className="admin-sort" onClick={onClick}>{label}{active?(direction==="asc"?<ChevronUp/>:<ChevronDown/>):null}</button>;
}

function Pager({page,total,pageSize,onPage,onPageSize}:{page:number;total:number;pageSize:number;onPage:(page:number)=>void;onPageSize:(size:number)=>void}) {
  const pages=Math.max(1,Math.ceil(total/pageSize)); const safe=Math.min(page,pages); const start=total?((safe-1)*pageSize)+1:0; const end=Math.min(safe*pageSize,total);
  return <footer className="admin-pagination"><span>{start}–{end} of {total}</span><label>Rows<select value={pageSize} onChange={e=>onPageSize(Number(e.target.value))}>{PAGE_SIZES.map(size=><option key={size}>{size}</option>)}</select></label><div><button aria-label="Previous page" disabled={safe===1} onClick={()=>onPage(safe-1)}><ChevronLeft/></button><span>Page {safe} of {pages}</span><button aria-label="Next page" disabled={safe===pages} onClick={()=>onPage(safe+1)}><ChevronRight/></button></div></footer>;
}

export default function AdminPortal({currentUserId}:{currentUserId:string}) {
  const { ask, confirm: confirmDialog, dialog } = useAppDialog();
  const [users,setUsers]=useState<AdminUser[]>([]), [complaints,setComplaints]=useState<Complaint[]>([]);
  const [draft,setDraft]=useState({email:"",password:"",fullName:"",role:"user"});
  const [busy,setBusy]=useState(""), [error,setError]=useState(""), [tab,setTab]=useState<"users"|"complaints">("users");
  const [userQuery,setUserQuery]=useState(""), [userRole,setUserRole]=useState("all"), [userStatus,setUserStatus]=useState("all"), [userSort,setUserSort]=useState("created"), [userDirection,setUserDirection]=useState<Direction>("desc"), [userPage,setUserPage]=useState(1), [userPageSize,setUserPageSize]=useState(10);
  const [complaintQuery,setComplaintQuery]=useState(""), [complaintStatus,setComplaintStatus]=useState("all"), [complaintSort,setComplaintSort]=useState("created"), [complaintDirection,setComplaintDirection]=useState<Direction>("desc"), [complaintPage,setComplaintPage]=useState(1), [complaintPageSize,setComplaintPageSize]=useState(10), [expandedComplaint,setExpandedComplaint]=useState("");

  const load=useCallback(async()=>{setBusy("load");setError("");try{const[u,c]=await Promise.all([fetch("/api/admin/users"),fetch("/api/complaints")]);const ud=await u.json(),cd=await c.json();if(!u.ok)throw new Error(ud.error);if(!c.ok)throw new Error(cd.error);setUsers(ud.users||[]);setComplaints(cd.complaints||[])}catch(e){setError((e as Error).message)}finally{setBusy("")}},[]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>setUserPage(1),[userQuery,userRole,userStatus,userPageSize]);
  useEffect(()=>setComplaintPage(1),[complaintQuery,complaintStatus,complaintPageSize]);
  const changeSort=(key:string,current:string,setKey:(key:string)=>void,direction:Direction,setDirection:(d:Direction)=>void)=>{if(key===current)setDirection(direction==="asc"?"desc":"asc");else{setKey(key);setDirection("asc")}};
  const selectTab=(next:"users"|"complaints")=>{setTab(next);requestAnimationFrame(()=>document.getElementById(`admin-${next}-tab`)?.focus())};
  const tabKeys=(event:KeyboardEvent<HTMLDivElement>)=>{if(event.key!=="ArrowLeft"&&event.key!=="ArrowRight")return;event.preventDefault();selectTab(tab==="users"?"complaints":"users")};

  const filteredUsers=useMemo(()=>users.filter(user=>{const role=user.app_metadata?.requestlab_role||"user";const suspended=Boolean(user.banned_until);return(!userQuery||`${user.user_metadata?.full_name||""} ${user.email||""}`.toLowerCase().includes(userQuery.toLowerCase()))&&(userRole==="all"||role===userRole)&&(userStatus==="all"||(userStatus==="suspended"?suspended:!suspended))}).sort((a,b)=>{const av=userSort==="name"?text(a.user_metadata?.full_name):userSort==="email"?text(a.email):userSort==="role"?text(a.app_metadata?.requestlab_role||"user"):new Date(a.created_at).getTime();const bv=userSort==="name"?text(b.user_metadata?.full_name):userSort==="email"?text(b.email):userSort==="role"?text(b.app_metadata?.requestlab_role||"user"):new Date(b.created_at).getTime();return(av<bv?-1:av>bv?1:0)*(userDirection==="asc"?1:-1)}),[users,userQuery,userRole,userStatus,userSort,userDirection]);
  const visibleUsers=filteredUsers.slice((Math.min(userPage,Math.max(1,Math.ceil(filteredUsers.length/userPageSize)))-1)*userPageSize,Math.min(userPage,Math.max(1,Math.ceil(filteredUsers.length/userPageSize)))*userPageSize);
  const filteredComplaints=useMemo(()=>complaints.filter(item=>(!complaintQuery||`${item.subject} ${item.user_email} ${item.message}`.toLowerCase().includes(complaintQuery.toLowerCase()))&&(complaintStatus==="all"||item.status===complaintStatus)).sort((a,b)=>{const av=complaintSort==="subject"?text(a.subject):complaintSort==="email"?text(a.user_email):complaintSort==="status"?text(a.status):new Date(a.created_at).getTime();const bv=complaintSort==="subject"?text(b.subject):complaintSort==="email"?text(b.user_email):complaintSort==="status"?text(b.status):new Date(b.created_at).getTime();return(av<bv?-1:av>bv?1:0)*(complaintDirection==="asc"?1:-1)}),[complaints,complaintQuery,complaintStatus,complaintSort,complaintDirection]);
  const visibleComplaints=filteredComplaints.slice((Math.min(complaintPage,Math.max(1,Math.ceil(filteredComplaints.length/complaintPageSize)))-1)*complaintPageSize,Math.min(complaintPage,Math.max(1,Math.ceil(filteredComplaints.length/complaintPageSize)))*complaintPageSize);

  const createUser=(e:FormEvent)=>{e.preventDefault();setBusy("create");setError("");fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setDraft({email:"",password:"",fullName:"",role:"user"});await load()}).catch(e=>setError(e.message)).finally(()=>setBusy(""))};
  const updateUser=async(id:string,body:Record<string,unknown>)=>{setBusy(id);setError("");try{const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...body})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e){setError((e as Error).message)}finally{setBusy("")}};
  const deleteUser=async(id:string)=>{if(!await confirmDialog({title:"Permanently delete this user?",message:"Their RequestLab account and owned data may be removed. This cannot be undone.",confirmLabel:"Delete user",destructive:true}))return;setBusy(id);const r=await fetch(`/api/admin/users?id=${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)setError(d.error);else await load();setBusy("")};
  const resetPassword=async(id:string)=>{const password=await ask({title:"Set a new password",message:"Use a temporary password the user can replace after signing in.",label:"New password",inputType:"password",minLength:12,confirmLabel:"Update password"});if(password)await updateUser(id,{password})};
  const updateComplaint=async(item:Complaint,status:string,adminResponse:string)=>{setBusy(item.id);const r=await fetch("/api/complaints",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,status,adminResponse})});const d=await r.json();if(!r.ok)setError(d.error);else await load();setBusy("")};

  return <main className="portal-page admin-page"><header className="portal-header"><BrandLogo/><nav><Link href="/app"><ArrowLeft size={15}/> Workspace</Link><Link href="/settings">Settings</Link><ThemeToggle/></nav></header><div className="admin-wrap"><div className="admin-title"><div><span className="section-kicker">System administration</span><h1>Admin portal</h1><p>Manage access, account status, roles, and user complaints.</p></div><button className="secondary" onClick={()=>void load()} disabled={busy==="load"}><RefreshCw className={busy==="load"?"spin":""}/> Refresh</button></div>{error&&<div className="portal-alert error" role="alert">{error}</div>}<div className="admin-stats"><div><Users/><strong>{users.length}</strong><span>Total users</span></div><div><ShieldCheck/><strong>{users.filter(u=>u.app_metadata?.requestlab_role==="admin").length}</strong><span>Administrators</span></div><div><MessageSquareWarning/><strong>{complaints.filter(c=>c.status!=="resolved").length}</strong><span>Open complaints</span></div></div>
  <div className="admin-tabs" role="tablist" aria-label="Administration sections" onKeyDown={tabKeys}><button id="admin-users-tab" role="tab" aria-controls="admin-users-panel" aria-selected={tab==="users"} tabIndex={tab==="users"?0:-1} className={tab==="users"?"active":""} onClick={()=>selectTab("users")}><Users/>User management<span>{users.length}</span></button><button id="admin-complaints-tab" role="tab" aria-controls="admin-complaints-panel" aria-selected={tab==="complaints"} tabIndex={tab==="complaints"?0:-1} className={tab==="complaints"?"active":""} onClick={()=>selectTab("complaints")}><MessageSquareWarning/>Complaints<span>{complaints.filter(c=>c.status!=="resolved").length}</span></button></div>
  {tab==="users"?<>
    <form className="portal-card admin-create" onSubmit={createUser}><header><Plus/><div><h2>Add a user</h2><p>Accounts created here are confirmed immediately.</p></div></header><div className="portal-fields"><label>Full name<input required value={draft.fullName} onChange={e=>setDraft({...draft,fullName:e.target.value})}/></label><label>Email<input required type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Temporary password<input required minLength={12} type="password" autoComplete="new-password" value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></label><label>Role<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="user">User</option><option value="admin">Administrator</option></select></label></div><button className="primary" disabled={busy==="create"}>{busy==="create"?<LoaderCircle className="spin"/>:<Plus/>} Create user</button></form>
    <section id="admin-users-panel" role="tabpanel" aria-labelledby="admin-users-tab" className="portal-card"><header><UserCog/><div><h2>User management</h2><p>Search, filter, sort, and manage RequestLab accounts.</p></div></header><div className="admin-data-toolbar"><label className="admin-search"><Search/><input aria-label="Search users" placeholder="Search name or email" value={userQuery} onChange={e=>setUserQuery(e.target.value)}/></label><select aria-label="Filter users by role" value={userRole} onChange={e=>setUserRole(e.target.value)}><option value="all">All roles</option><option value="user">Users</option><option value="admin">Administrators</option></select><select aria-label="Filter users by status" value={userStatus} onChange={e=>setUserStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div><div className="admin-table"><div className="admin-row admin-row-head"><SortButton label="User" active={userSort==="name"} direction={userDirection} onClick={()=>changeSort("name",userSort,setUserSort,userDirection,setUserDirection)}/><SortButton label="Role" active={userSort==="role"} direction={userDirection} onClick={()=>changeSort("role",userSort,setUserSort,userDirection,setUserDirection)}/><SortButton label="Created" active={userSort==="created"} direction={userDirection} onClick={()=>changeSort("created",userSort,setUserSort,userDirection,setUserDirection)}/><span>Actions</span></div>{visibleUsers.map(user=><div className="admin-row" key={user.id}><span><strong>{user.user_metadata?.full_name||"Unnamed user"}</strong><small>{user.email}</small>{user.banned_until&&<em>Suspended</em>}</span><select value={user.app_metadata?.requestlab_role||"user"} disabled={user.id===currentUserId||busy===user.id} onChange={e=>void updateUser(user.id,{role:e.target.value})}><option value="user">User</option><option value="admin">Admin</option></select><span>{new Date(user.created_at).toLocaleDateString()}</span><span className="row-actions"><button className="secondary" onClick={()=>void resetPassword(user.id)}>Password</button><button className="secondary" disabled={user.id===currentUserId} onClick={()=>void updateUser(user.id,{banned:!user.banned_until})}>{user.banned_until?"Restore":"Suspend"}</button><button className="icon-button danger" aria-label={`Delete ${user.email}`} disabled={user.id===currentUserId} onClick={()=>void deleteUser(user.id)}><Trash2/></button></span></div>)}{!visibleUsers.length&&<div className="admin-empty">No users match these filters.</div>}</div><Pager page={userPage} total={filteredUsers.length} pageSize={userPageSize} onPage={setUserPage} onPageSize={setUserPageSize}/></section>
  </>:<section id="admin-complaints-panel" role="tabpanel" aria-labelledby="admin-complaints-tab" className="portal-card"><header><MessageSquareWarning/><div><h2>Complaints inbox</h2><p>Search, prioritize, and respond to user reports.</p></div></header><div className="admin-data-toolbar"><label className="admin-search"><Search/><input aria-label="Search complaints" placeholder="Search subject, user, or message" value={complaintQuery} onChange={e=>setComplaintQuery(e.target.value)}/></label><select aria-label="Filter complaints by status" value={complaintStatus} onChange={e=>setComplaintStatus(e.target.value)}><option value="all">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></div><div className="admin-table complaint-table"><div className="complaint-row admin-row-head"><SortButton label="Subject" active={complaintSort==="subject"} direction={complaintDirection} onClick={()=>changeSort("subject",complaintSort,setComplaintSort,complaintDirection,setComplaintDirection)}/><SortButton label="Reporter" active={complaintSort==="email"} direction={complaintDirection} onClick={()=>changeSort("email",complaintSort,setComplaintSort,complaintDirection,setComplaintDirection)}/><SortButton label="Status" active={complaintSort==="status"} direction={complaintDirection} onClick={()=>changeSort("status",complaintSort,setComplaintSort,complaintDirection,setComplaintDirection)}/><SortButton label="Submitted" active={complaintSort==="created"} direction={complaintDirection} onClick={()=>changeSort("created",complaintSort,setComplaintSort,complaintDirection,setComplaintDirection)}/><span>Action</span></div>{visibleComplaints.map(item=><div className="complaint-table-item" key={item.id}><div className="complaint-row"><strong>{item.subject}</strong><span>{item.user_email}</span><span className={`status-badge ${item.status}`}>{item.status.replace("_"," ")}</span><span>{new Date(item.created_at).toLocaleDateString()}</span><button className="secondary" aria-expanded={expandedComplaint===item.id} onClick={()=>setExpandedComplaint(expandedComplaint===item.id?"":item.id)}>{expandedComplaint===item.id?"Close":"Review"}</button></div>{expandedComplaint===item.id&&<ComplaintEditor item={item} busy={busy===item.id} onSave={updateComplaint}/>}</div>)}{!visibleComplaints.length&&<div className="admin-empty">No complaints match these filters.</div>}</div><Pager page={complaintPage} total={filteredComplaints.length} pageSize={complaintPageSize} onPage={setComplaintPage} onPageSize={setComplaintPageSize}/></section>}</div>{dialog}</main>;
}

function ComplaintEditor({item,busy,onSave}:{item:Complaint;busy:boolean;onSave:(item:Complaint,status:string,response:string)=>Promise<void>}) { const[status,setStatus]=useState(item.status);const[response,setResponse]=useState(item.admin_response||"");return <article className="complaint-editor"><div><span><strong>{item.subject}</strong><small>{item.user_email} · {new Date(item.created_at).toLocaleString()}</small></span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></div><p>{item.message}</p><textarea placeholder="Write a response to the user…" value={response} onChange={e=>setResponse(e.target.value)}/><button className="primary" disabled={busy} onClick={()=>void onSave(item,status,response)}>{busy?<LoaderCircle className="spin"/>:"Save response"}</button></article> }
